management:
  security:  
    enabled: false    


server:
   port: 8079
   ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/yerevan.p12
    key-store-password: yerevan
    key-alias: yerevan  
   tomcat:
     max-http-post-size: 6291456
     


spring:
  application:
    name: zuul
  servlet:
   multipart:
      max-file-size: 5MB
      max-request-size: 5MB


zuul:
  prefix: /world/gateway
  routes:
    yerevan:
      path: /yerevan/**   
      serviceId: YEREVAN       
      
            
#
#    
#
#ribbon: 
#  TrustStore: classpath:keystore/yerevan.p12
#  TrustStorePassword : yerevan
#  ReadTimeout: 60000
#  IsSecure: true
#  MaxAutoRetries: 10
  
yerevan:
   ribbon:
     ReadTimeout: 30000
  
  
eureka:
  instance:  
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    leaseExpirationDurationInSeconds: 3
  client:
    enabled: true
    registryFetchIntervalSeconds: 5   
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

